### ISSUE TITLE
Treats external packages as internal

### ISSUE THREAD

**Issue by chbndrhnns** [facebookexperimental/usort#196]
Given the MWE at [1], when I run `ufmt format`, I expect the package `provider` to be above `consumer` as `provider` comes from an external package. However, it's just sorted alphabetically.

[1] https://github.com/chbndrhnns/mwe-ufmt-external

**Comment by thatch** [comment]
I suspect this has to do with your working dir and how you're running "ufmt format."  Especially if you have two projects in the same repo.

The first-party detection can pick at most one name, and I suspect it's picking zero.  See the implementation at https://github.com/facebookexperimental/usort/blob/main/usort/config.py#L113

See https://usort.readthedocs.io/en/stable/guide.html#tool-usort-known for how you can explicitly list first-party names (and disable `first_party_detection` if it behaves inconsistently for you).

**Comment by chbndrhnns** [comment]
You are right about behaviour; with this config it works fine:

```toml
[tool.usort.known]
first_party = ["consumer"]
```

And it works out of the box when sorting in the actual production package ("consumer").

Would it be an option to extend the auto-detection by leaving the "tests" or "test" package and see if its parent (the project name) is duplicated in the root directory? This way, sorting would also work in some more cases in the tests package without additional configuration. 

Example:
"consumer" is the name of the project directory AND the name of a directory what you call "first_party".

```
consumer/
├── README.rst
├── consumer
│   ├── __init__.py
│   └── other.py
├── poetry.lock
├── pyproject.toml
└── tests
    ├── __init__.py
    └── test_consumer.py
```

**Comment by thatch** [comment]
> Would it be an option to extend the auto-detection by leaving the "tests" or "test" package and see if its parent (the project name) is duplicated in the root directory?

Do I understand correctly that you're saying:

```shell-session
$ git clone https://github.com/example/foo
$ ufmt foo/tests # behavior change when foo/foo exists
```

I'm not immediately in favor, more because of it being magic than it being computationally difficult.  There are two core values that this doesn't go along with:

1. That formatting should be "universal" -- it should produce the same result on any OS, for any working dir, and for a git export vs live git checkout (thus only paths from the pyproject.toml down can matter).
2. That features should be easy to explain in docs, and their configuration should focus on user intent.

People can provide another arg to `git clone` so we can't rely on the dirname matching the original repo name.  There are also examples like

* [python-zstandard](https://github.com/indygreg/python-zstandard/) that has `zstandard`
* [poetry-core](https://github.com/python-poetry/poetry-core) that has `src/poetry/core`

It's too bad package_dir and packages didn't become a part of PEP 621, as that would have provided a standards-based universal way to infer the main project name even for subdirs like `tests`.

What we do in `usort` (and many other projects that @jreese has been involved in) is put the tests under the main package.  I don't know if this works for your two-projects-in-the-same-repo case, but that (or `tool.usort.known.first-party`) would be my suggestions for getting this to work for you.

**Comment by chbndrhnns** [comment]
I understood that there is no universal standard which would my suggested behaviour work for most cases. So I am fine with configuring the first-party option to make it work.

Currently, I am using isort + black which seems to work without additional configuration wrt the package names. But maybe isort implements some magic here. I haven't checked the implementation yet.

**Comment by thatch** [comment]
Relevant isort code is

* https://github.com/PyCQA/isort/blob/main/isort/settings.py#L458 (src_path appears to be the src/ type prefix, relative to where it found the config)
* https://github.com/PyCQA/isort/blob/main/isort/place.py#L72

I don't follow what happens with the namespace section, but the rest is pretty much what I expect.

Ours is much simpler with the `known` escape hatch to be explicit about it.  See https://github.com/facebookexperimental/usort/blob/main/usort/config.py#L113
