### ISSUE TITLE
Handle encoding correctly

### ISSUE THREAD

**Issue by thatch** [facebookexperimental/usort#46]
Right now read_text uses the system encoding only.  We should read bytes and allow libcst to decode/encode.

**Comment by jreese** [comment]
For posterity: `pathlib.Path.read_text()` with no arguments uses the encoding specified by `locale.getpreferredencoding()`. That value defaults to UTF-8 on Linux and macOS, but instead defaults to cp1252 on Windows. PEP 3120 specifies UTF-8 as the default encoding for Python sources, but still allows for PEP 263 coding markers at the top of the file in a different encoding is desired. This means we can't use `read_text()` without specifying an encoding, and we can't use `read_text("utf-8")` because it might not be UTF-8, but we also don't know the correct encoding without first reading the bytes and inspecting the contents for PEP 263 coding markers. 

For our specific use case, LibCST already handles PEP 263 markers, and µsort already encodes back to bytes when asking LibCST to parse the contents, so µsort should probably just be reading bytes in the first place.

Test case that exposes the current behavior as incorrect on Windows:

```diff
diff --git a/usort/tests/cli.py b/usort/tests/cli.py
index 9574c0e..3067afb 100644
--- a/usort/tests/cli.py
+++ b/usort/tests/cli.py
@@ -7,7 +7,7 @@ import os
 import unittest
 from contextlib import contextmanager
 from pathlib import Path
-from typing import Generator
+from typing import AnyStr, Generator

 import volatile
 from click.testing import CliRunner
@@ -24,11 +24,14 @@ def chdir(new_dir: str) -> Generator[None, None, None]:


 @contextmanager
-def sample_contents(s: str) -> Generator[str, None, None]:
+def sample_contents(s: AnyStr) -> Generator[str, None, None]:
     with volatile.dir() as dtmp:
         ptmp = Path(dtmp)
         (ptmp / "pyproject.toml").write_text("")
-        (ptmp / "sample.py").write_text(s)
+        if isinstance(s, bytes):
+            (ptmp / "sample.py").write_bytes(s)
+        else:
+            (ptmp / "sample.py").write_text(s)
         yield dtmp


@@ -155,6 +158,33 @@ import os
         )
         self.assertEqual(result.exit_code, 1)

+    def test_format_unicode_error(self) -> None:
+        """File contains invalid unicode sequences"""
+        with sample_contents(b"print('hello \xd8')\n") as dtmp:
+            runner = CliRunner()
+            with chdir(dtmp):
+                result = runner.invoke(main, ["format", "."])
+
+        self.assertRegex(
+            result.output,
+            r"Error sorting sample\.py: '.+' codec can't decode byte",
+        )
+        self.assertEqual(result.exit_code, 1)
+
     def test_format_with_change(self) -> None:
         with sample_contents("import sys\nimport os\n") as dtmp:
             runner = CliRunner()
```

The test will pass on Linux and macOS as `\xd8` is an invalid character in UTF-8, but will "fail" on Windows because the default encoding cp1252 can "successfully" decode those bytes.
